identifier: sh.cider.plugin-template-wip
name: Example Plugin
description: Shows off some of the working plugin API draft
author: ciderapp
repo: https://github.com/ciderapp/plugin-template-wip
entry:
  "plugin.js":
    type: main